In [12]:
import numpy as np
import math
#Use the following code for the questions below:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

#1. How many negative numbers are there?
print(a[a < 0])
print(f'There are {len(a[a < 0])} negative numbers in array')

[-2 -1 -6 -7]
There are 4 negative numbers in array


In [14]:
#2. How many positive numbers are there?

print(a[a > 0])
print(f'There are {len(a[a > 0])} positive numbers in array')

[ 4 10 12 23  3]
There are 5 positive numbers in array


In [44]:
#3. How many even positive numbers are there?

positive = a[a > 0]
print(positive)
even  = positive[positive % 2 == 0]
print(even)
print(f'There are {len(even)} positive even numbers in array')




[ 4 10 12 23  3]
[ 4 10 12]
There are 3 positive even numbers in array


In [46]:
#4. If you were to add 3 to each data point, how many positive numbers would there be?
print(a)
a_plus_3 = a + 3
a_plus_3


[ 4 10 12 23 -2 -1  0  0  0 -6  3 -7]


array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [ ]:
#5. If you squared each number, what would the new mean and standard deviation be?



In [ ]:
#6. A common statistical operation on a dataset is centering. 
#This means to adjust the data such that the mean of the data is 0.
#This is done by subtracting the mean from each data point. 
#Center the data set. See this link for more on centering.



In [ ]:
#7. Calculate the z-score for each data point. Recall that the z-score is given by:

#Z = (x − μ) / σ

In [ ]:
#8. Copy the setup and exercise directions
#from More Numpy Practice into your numpy_exercises.py and add your solutions.



In [ ]:
#Awesome Bonus For much more practice with numpy, 
#Go to https://github.com/rougier/numpy-100 and click the "Fork" icon in the upper-right
#of the screen to fork the repo. This makes a copy of the repo onto your own account. 
#Next, clone your fork https://github.com/your-username/numpy-100 down to your machine.
#Work through, add, commit, and push your solutions to your own repo.

